//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SqlxMigrations struct {
	Version       int64 `sql:"primary_key"`
	Description   string
	InstalledOn   time.Time
	Success       bool
	Checksum      []byte
	ExecutionTime int64
}
