//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type League struct {
	LeagueID         string `sql:"primary_key"`
	QueueType        string
	Tier             string
	Rank             string
	SummonerID       string `sql:"primary_key"`
	LeaguePoints     int32
	Wins             int32
	Losses           int32
	Veteran          bool
	Inactive         bool
	Freshblood       bool
	Hotstreak        bool
	LastLeagueUpdate *time.Time
}
