//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RankedSeason struct {
	Rid               int32 `sql:"primary_key"`
	RankedSeasonID    int32
	TotalRankedSplits int32
	SplitID           int32
	StartDate         time.Time
	EndDate           time.Time
}
