//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Socials struct {
	ID            int32 `sql:"primary_key"`
	PlayerName    string
	DiscordLink   *string
	InstagramLink *string
	TiktokLink    *string
	TwitterLink   *string
	TwitchLink    *string
	YoutubeLink   *string
	IconName      *string
}
