//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SummonerMatches struct {
	Puuid                     string `sql:"primary_key"`
	MatchID                   string `sql:"primary_key"`
	GameMode                  *string
	GameType                  *string
	QueueID                   *string
	Kills                     *int32
	Assists                   *int32
	Deaths                    *int32
	Kda                       *float64
	KillParticipation         *float64
	Processed                 *bool
	GameStartTime             *time.Time
	GameEndTime               *time.Time
	GameEndedInEarlySurrender *bool
	Win                       *bool
}
