//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Summoner struct {
	Puuid              string `sql:"primary_key"`
	GameName           string
	TagLine            string
	LastMatchUpdate    *time.Time
	LastSummonerUpdate *time.Time
	ID                 *string
	AccountID          *string
	ProfileIconID      *int32
	SummonerLevel      *int64
	RevisionDate       *time.Time
	PlayerName         *string
}
