//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SummonerNameHistory struct {
	Puuid      string `sql:"primary_key"`
	GameName   string
	TagLine    string
	RenameDate time.Time `sql:"primary_key"`
}
