//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	//SqlxMigrations = SqlxMigrations.FromSchema(schema)
	League = League.FromSchema(schema)
	Match = Match.FromSchema(schema)
	Player = Player.FromSchema(schema)
	RankedSeason = RankedSeason.FromSchema(schema)
	Socials = Socials.FromSchema(schema)
	Summoner = Summoner.FromSchema(schema)
	SummonerMatches = SummonerMatches.FromSchema(schema)
	SummonerNameHistory = SummonerNameHistory.FromSchema(schema)
}
