// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	SQLXMigrations      string
	League              string
	Match               string
	Player              string
	RankedSeason        string
	Socials             string
	Summoner            string
	SummonerMatches     string
	SummonerNameHistory string
}{
	SQLXMigrations:      "_sqlx_migrations",
	League:              "league",
	Match:               "match",
	Player:              "player",
	RankedSeason:        "ranked_season",
	Socials:             "socials",
	Summoner:            "summoner",
	SummonerMatches:     "summoner_matches",
	SummonerNameHistory: "summoner_name_history",
}
